# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setStyleSheet("QPushButton{\n"
"background-color: red;\n"
"min-height:40px;\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.cvlabel = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cvlabel.sizePolicy().hasHeightForWidth())
        self.cvlabel.setSizePolicy(sizePolicy)
        self.cvlabel.setMinimumSize(QtCore.QSize(640, 480))
        self.cvlabel.setMaximumSize(QtCore.QSize(640, 480))
        self.cvlabel.setObjectName("cvlabel")
        self.gridLayout.addWidget(self.cvlabel, 3, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.page)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.probeButton = QtWidgets.QPushButton(self.verticalFrame)
        self.probeButton.setObjectName("probeButton")
        self.verticalLayout.addWidget(self.probeButton)
        self.scanButton = QtWidgets.QPushButton(self.verticalFrame)
        self.scanButton.setObjectName("scanButton")
        self.verticalLayout.addWidget(self.scanButton)
        self.verticalLayout_2.addWidget(self.verticalFrame)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalFrame1 = QtWidgets.QFrame(self.page_4)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalFrame1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalFrame1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalFrame1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_7.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalFrame1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_7.addWidget(self.pushButton_12)
        self.verticalLayout_8.addWidget(self.verticalFrame1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalFrame2 = QtWidgets.QFrame(self.page_2)
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.autoSearchButton = QtWidgets.QPushButton(self.verticalFrame2)
        self.autoSearchButton.setObjectName("autoSearchButton")
        self.verticalLayout_3.addWidget(self.autoSearchButton)
        self.clickAndProbeButton = QtWidgets.QPushButton(self.verticalFrame2)
        self.clickAndProbeButton.setObjectName("clickAndProbeButton")
        self.verticalLayout_3.addWidget(self.clickAndProbeButton)
        self.manProbeButton = QtWidgets.QPushButton(self.verticalFrame2)
        self.manProbeButton.setObjectName("manProbeButton")
        self.verticalLayout_3.addWidget(self.manProbeButton)
        self.verticalLayout_4.addWidget(self.verticalFrame2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalFrame3 = QtWidgets.QFrame(self.page_3)
        self.verticalFrame3.setObjectName("verticalFrame3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalFrame3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalFrame3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_6.addWidget(self.verticalFrame3)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.gridFrame)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.goBackButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.goBackButton.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.goBackButton.setObjectName("goBackButton")
        self.horizontalLayout.addWidget(self.goBackButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.horizontalFrame, 0, 0, 1, 1)
        self.instructionLabel = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("Quicksand Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setObjectName("instructionLabel")
        self.gridLayout.addWidget(self.instructionLabel, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gridFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cvlabel.setText(_translate("MainWindow", "Camera"))
        self.probeButton.setText(_translate("MainWindow", "Probe"))
        self.scanButton.setText(_translate("MainWindow", "Scan"))
        self.pushButton_9.setText(_translate("MainWindow", "Complete scan"))
        self.pushButton_10.setText(_translate("MainWindow", "Partial scans"))
        self.pushButton_11.setText(_translate("MainWindow", "Circumference scan"))
        self.pushButton_12.setText(_translate("MainWindow", "Geometric tolerances"))
        self.autoSearchButton.setText(_translate("MainWindow", "Automatic Search"))
        self.clickAndProbeButton.setText(_translate("MainWindow", "Click and probe"))
        self.manProbeButton.setText(_translate("MainWindow", "Manual Probe"))
        self.pushButton_6.setText(_translate("MainWindow", "Hole"))
        self.pushButton_7.setText(_translate("MainWindow", "Rectangle"))
        self.goBackButton.setText(_translate("MainWindow", "Go back"))
        self.instructionLabel.setText(_translate("MainWindow", "Follow instruction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

